import type { SpriteAsset, SoundAsset, SoundChannelType } from "../../types";
import type { MapExport, RomAllocationPlan } from "./types";
import { sanitizeName } from "./utils";

const CHANNEL_NUM: Record<SoundChannelType, number> = {
  PULSE1: 1, PULSE2: 2, WAVE: 3, NOISE: 4,
};

const CHANNEL_LABEL: Record<SoundChannelType, string> = {
  PULSE1: "GBT_CH_PULSE1", PULSE2: "GBT_CH_PULSE2",
  WAVE:   "GBT_CH_WAVE",   NOISE:  "GBT_CH_NOISE",
};

export const buildHeader = (
  projectName: string,
  mapExports: MapExport[],
  sprites: SpriteAsset[],
  romPlan: RomAllocationPlan,
  sounds: SoundAsset[],
): string => {
  const safeProjectName = sanitizeName(projectName).toUpperCase();
  let content = `// GBDK-2020 Header — generated by Cartridge Editor\n`;
  content += `#ifndef __${safeProjectName}_H__\n#define __${safeProjectName}_H__\n`;
  content += `#include <gb/gb.h>\n#include <stdint.h>\n\n`;

  content += `#define ${safeProjectName}_ROM_BANK_COUNT ${romPlan.banks.length}\n`;
  content += `#define ${safeProjectName}_ROM_TOTAL_BYTES ${romPlan.totalBytes}\n\n`;

  // ── Map types ──────────────────────────────────────────────────────────────
  content += "typedef enum { GBT_DIR_UP, GBT_DIR_DOWN, GBT_DIR_LEFT, GBT_DIR_RIGHT } gbt_dir_t;\n\n";

  content += "typedef struct { uint8_t bank; const unsigned char *data; } GBT_CHUNK_REF;\n\n";

  content += "typedef struct GBT_MAP {\n";
  content += "    uint8_t tiles_bank;\n";
  content += "    const unsigned char *tiles;\n";
  content += "    uint16_t tile_count;\n";
  content += "    uint8_t world_bank;\n";
  content += "    const GBT_CHUNK_REF *world;\n";
  content += "    uint8_t world_w;\n";
  content += "    uint8_t world_h;\n";
  content += "    uint16_t spawn_x;\n";
  content += "    uint16_t spawn_y;\n";
  content += "    uint8_t collision_bank;\n";
  content += "    const unsigned char *collision;\n";
  content += "} GBT_MAP;\n\n";

  content += "typedef struct GBT_CAMERA_CTRL {\n";
  content += "    uint16_t x;\n";
  content += "    uint16_t y;\n";
  content += "    const GBT_MAP *map;\n";
  content += "} GBT_CAMERA_CTRL;\n\n";

  // ── Sprite types ───────────────────────────────────────────────────────────
