import { useEffect } from "react";
import { useStore } from "../../store";
import { MapCanvas } from "./map-editor/MapCanvas";
import { MapEditorHeader } from "./map-editor/MapEditorHeader";
import { MapToolBar } from "./map-editor/MapToolBar";
import { MapAssetPanel } from "./map-editor/MapAssetPanel";
import { LayersPanel } from "./map-editor/LayersPanel";
import { useMapEditorShortcuts } from "./map-editor/useMapEditorShortcuts";
import { useMapEditorInteraction } from "./map-editor/useMapEditorInteraction";
