import { useCallback, useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open, save } from "@tauri-apps/plugin-dialog";
import { TilePixelEditor } from "./components/editors/TilePixelEditor";
import { MapEditor } from "./components/editors/MapEditor";
import { SpriteStudio } from "./components/editors/SpriteStudio";
import { SoundStudio } from "./components/editors/SoundStudio";
import { Settings } from "./components/editors/Settings";
import { AppLayout } from "./components/layout/AppLayout";
import type { StatusTone } from "./components/layout/StatusBar";
import { MapGallery } from "./components/panels/MapGallery";
import { Palette, Toolbox } from "./components/panels/Toolbar";
import { TilesetPanel } from "./components/panels/TilesetPanel";
import { ShortcutsModal } from "./components/ui/ShortcutsModal";
import { ExportPreviewModal } from "./components/ui/ExportPreviewModal";
import { TemplateGallery } from "./components/ui/TemplateGallery";
import { generateCFile, generateHFile } from "./services/exportService";
import {
import { useStore } from "./store";
import { useKeyboardShortcuts } from "./store/hooks/useKeyboardShortcuts";
import "./App.css";
